### ISSUE TITLE
Update the logged in member "code": "rest_user_invalid_id"

### ISSUE THREAD

**Issue by ranfen** [buddypress/BP-REST#456] opened 2022-08-29 13:01 UTC
Hi I tried to update the logged-in user Display name using REST API I got this Error
Update the logged in member
 "code": "rest_user_invalid_id",
    "message": "Invalid user ID.",

i fellowed the documentation:  [Update the logged in member](https://developer.buddypress.org/bp-rest-api/reference/members/#definition-7)

![iScreen Shoter - 20220829085415708](https://user-images.githubusercontent.com/80561800/187206512-c3adfc48-a70e-4d58-ad77-2ee9ff0810fa.jpg)

**Comment by renatonascalves** [comment] 2022-08-29 13:25
Are you authenticated? This error implies the current user is not logged in.

**Comment by ranfen** [comment] 2022-08-29 13:46
> 

Yes I am all the other API endpoints works great

**Comment by renatonascalves** [comment] 2022-10-02 00:01
@ranfen I can't reproduce this issue. 🤔

**Comment by ranfen** [comment] 2022-10-13 09:46
> @ranfen I can't reproduce this issue. 🤔

So what should we do?

**Comment by imath** [comment] 2022-12-06 05:28
I confirm @renatonascalves test. The endpoint behaves as expected. I've just tested using the code we're suggesting in https://developer.buddypress.org/bp-rest-api/reference/members/#update-the-logged-in-member

@ranfen I advise you to check the nonce header has been sent by your request.

For now and with no other inputs. I'm closing this issue.

**Closed by imath** 2022-12-06 05:28 UTC
