### ISSUE TITLE
Private messages pagination

### ISSUE THREAD

**Issue by durdenx** [buddypress/BP-REST#409] opened 2021-06-24 09:00 UTC
I don't see how to paginate large conversations in a Thread. All messages are included in the thread, and i don't think it will scale, especially in a single thread conversation app.

**Comment by renatonascalves** [comment] 2021-06-24 11:59
You can actually paginate a thread: https://developer.buddypress.org/bp-rest-api/reference/private-messaging/#list-messages-threads

Going to close this issue as invalid but feel free to ask any questions.:)

**Comment by durdenx** [comment] 2021-06-24 23:33
@renatonascalves Thank you for your answer. 

I was talking about the `messages` field in a specific thread. It’s an array containing all the messages of the thread. 

messagesarray | List of message objects for the Thread. Read only Context: view, edit
-- | --

**Comment by renatonascalves** [comment] 2021-06-25 02:26
That's correct! And I see your point. I'll update that.

**Comment by renatonascalves** [comment] 2021-07-10 00:34
It appears that paginating messages from a thread is not part of BuddyPress core. I created this ticket https://buddypress.trac.wordpress.org/ticket/8508 to add this enhancement.

After that's done, I'll apply it here.

**Comment by renatonascalves** [comment] 2021-12-04 22:35
Support added! :)

**Comment by berzki** [comment] 2024-04-04 14:41
@renatonascalves Any tips on how to use this using Postman? I am trying to retrieve a thread, for example, /wp-json/buddypress/v1/messages/123 and trying to page it as it is a large thread. Are you able to give an example as to how paging works within a thread? I was not able to find any examples in the documentation. Cheers! :)

**Comment by renatonascalves** [comment] 2024-04-04 16:15
@berzki Have you looked at the documentation? You can use the `messages_page` and `messages_per_page` to paginate messages of a large thread.

https://developer.buddypress.org/bp-rest-api/reference/private-messaging/#list-messages-threads

**Comment by berzki** [comment] 2024-04-04 20:40
@renatonascalves Yes, but I am getting the whole thread back when doing the following. I am trying to get approx. 50 messages within a thread that has a few thousand entries.

```
GET /wp-json/buddypress/v1/messages/123
{
    "messages_page": "1",
    "messages_per_page": "50"
}
```

**Comment by renatonascalves** [comment] 2024-04-05 02:34
@berzki That looks like a bug then. What's your BuddyPress version?

**Comment by berzki** [comment] 2024-04-05 03:13
I am using version 12.3.0 of BuddyPress. I can paginate the list of message threads (the one in your link) with no problems, but not when retrieving a specific message thread.

Thanks for your support @renatonascalves

**Comment by renatonascalves** [comment] 2024-04-21 20:54
@berzki Confirmed. Apparently, I forgot to add support for pagination when getting a single thread message. 

Could you test [this pr](https://github.com/buddypress/BP-REST/pull/503) please?

**Comment by berzki** [comment] 2024-04-22 03:18
@renatonascalves Working fine, cheers. Is it possible to add an order? Like asc and desc. To get the total pages, how do I go about that? X-WP-Total* headers are not being returned in the single thread. I would like to load older messages when the user scrolls up in the chat. What would you recommend here?

**Comment by renatonascalves** [comment] 2024-04-22 03:51
@berzki Ops! Good catch. I totally forgot about the pagination headers. Added. Also, it's possible to sort the messages.

Could you test the pull request again?

**Comment by berzki** [comment] 2024-04-22 04:25
@renatonascalves Tested updated PR and I can see the headers now. Fantastic! Looking closer at the order, you're right. I can sort the single thread. Is it possible to sort the message list in asc and desc? Asking because it doesn't work for me in case it is possible.

**Comment by berzki** [comment] 2024-04-22 05:57
By the above, I mean /messages. The list of all messages.

**Comment by berzki** [comment] 2024-04-23 01:50
Thanks for the insight. Would be very handy to add separately if it's something the team would be interested in? Understandable if not!

**Comment by renatonascalves** [comment] 2024-04-25 01:33
I have a few updates to the Messages component regarding pagination. It's possible we might be able to add this later, but not now.

**Closed** 2024-05-04 13:29 UTC
Labels: enhancement, Component: Messages
