### ISSUE TITLE
Notification delete bug

### ISSUE THREAD

**Issue by modemlooper** [buddypress/BP-REST#397] opened 2021-06-09 16:01 UTC
The documentation says to send DELETE request to: `buddypress/v1/notifications/<id>`

But you actually have to pass an id param as well `buddypress/v1/notifications/<id>?id=<id>`

If you just send `buddypress/v1/notifications/<id>` it will return true like it deleted the notification but it doesn't really delete as the id param is missing.

code needs a better check if param is missing and send a did not delete response.

https://developer.buddypress.org/bp-rest-api/reference/screen-notifications/#definition-5

**Comment by renatonascalves** [comment] 2021-06-09 18:02
Maybe the larger issue is why `if ( ! BP_Notifications_Notification::delete( array( 'id' => $notification->id ) ) ) {` is not returning `false`.

**Comment by renatonascalves** [comment] 2021-06-09 18:02
I'm going to take a look at this later. Tks for reporting. :)

**Comment by renatonascalves** [comment] 2021-06-15 02:57
@modemlooper 

I can't reproduce this behavior you are facing. I'm able to pass the id without adding a param for that and the request is checking if the notification exists or not and returning the proper error response.

<img width="1165" alt="Screen Shot 2021-06-14 at 23 53 43" src="https://user-images.githubusercontent.com/19148962/121985939-1193e800-cd6c-11eb-8e39-c1ff466ee8f3.png">

**Comment by renatonascalves** [comment] 2021-06-15 03:00
I also reviewed this component unit tests since it micmicks what I did there and it seems to be okay. So I wonder what other variable would be in place so that it is not working for you.

**Comment by modemlooper** [comment] 2021-06-15 16:36
I'll check again

**Comment by renatonascalves** [comment] 2021-06-15 18:32
Tks! About your point about `params`, I agree. It's on my list to upgrade that in the plugin. But it is not related to this issue here. :)

**Comment by renatonascalves** [comment] 2021-06-15 18:37
Created #401 to handle your suggestion. :)

**Comment by renatonascalves** [comment] 2021-07-02 01:52
I'm closing this issue as invalid, for now. :)

**Closed by renatonascalves** 2021-07-02 01:52 UTC
Labels: Component: Notification, bug
